# Form implementation generated from reading ui file 'FirstWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GrafFunk(object):
    def setupUi(self, GrafFunk):
        GrafFunk.setObjectName("GrafFunk")
        GrafFunk.resize(640, 516)
        GrafFunk.setMinimumSize(QtCore.QSize(640, 516))
        GrafFunk.setMaximumSize(QtCore.QSize(649, 516))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("965949.160.webp"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        GrafFunk.setWindowIcon(icon)
        GrafFunk.setStyleSheet("background-color: rgb(100, 129, 68);")
        self.centralwidget = QtWidgets.QWidget(parent=GrafFunk)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 60, 461, 61))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(198, 214, 178);\n"
"border: 5px;\n"
"border-style: solid;\n"
"border-radius: 20px;\n"
"border-color: rgb(136, 172, 97);\n"
"color: rgb(136, 172, 97);")
        self.label.setObjectName("label")
        self.HRButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.HRButton.setGeometry(QtCore.QRect(100, 350, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(11)
        self.HRButton.setFont(font)
        self.HRButton.setStyleSheet("background-color: rgb(198, 214, 178);\n"
"border: 5px;\n"
"border-style: solid;\n"
"border-radius: 20px;\n"
"border-color: rgb(136, 172, 97);\n"
"color: rgb(136, 172, 97);")
        self.HRButton.setObjectName("HRButton")
        self.RRButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RRButton.setGeometry(QtCore.QRect(340, 350, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Heavy")
        font.setPointSize(11)
        self.RRButton.setFont(font)
        self.RRButton.setStyleSheet("background-color: rgb(198, 214, 178);\n"
"border: 5px;\n"
"border-style: solid;\n"
"border-radius: 20px;\n"
"border-color: rgb(136, 172, 97);\n"
"color: rgb(136, 172, 97);")
        self.RRButton.setObjectName("RRButton")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 140, 161, 181))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("965949.160.webp"))
        self.label_2.setObjectName("label_2")
        GrafFunk.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=GrafFunk)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 26))
        self.menubar.setObjectName("menubar")
        GrafFunk.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=GrafFunk)
        self.statusbar.setObjectName("statusbar")
        GrafFunk.setStatusBar(self.statusbar)

        self.retranslateUi(GrafFunk)
        QtCore.QMetaObject.connectSlotsByName(GrafFunk)

    def retranslateUi(self, GrafFunk):
        _translate = QtCore.QCoreApplication.translate
        GrafFunk.setWindowTitle(_translate("GrafFunk", "Графики функций"))
        self.label.setText(_translate("GrafFunk", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600;\">Графики функций</span></p></body></html>"))
        self.HRButton.setText(_translate("GrafFunk", "Ручной режим"))
        self.RRButton.setText(_translate("GrafFunk", "Режим рандома"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GrafFunk = QtWidgets.QMainWindow()
    ui = Ui_GrafFunk()
    ui.setupUi(GrafFunk)
    GrafFunk.show()
    sys.exit(app.exec())
